env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: error
  semi: off
  quotes: ['error', 'single']
  indent: ['error', 4]
