env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: error
  semi: ['error', 'never']
  quotes: ['error', 'single']
  indent: ['error', 2 ,{ "SwitchCase": 1 }]
  no-undef: error
global:
  middleware: true
  logger: true

