const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const { EventEmitter } = require('events');

let mainWindow = null;
let mockSocketInstance = null;
let backendAPIs = null;

// Dynamic loader for ES modules from our CJS script
async function bootstrapBackend() {
  console.log('[Electron Main] Starting database, config, and server modules...');
  
  // Import app.js to trigger the full startup flow (db generation, cron scheduler, etc.)
  await import('./app.js');
  
  // Import config to retrieve the initialized port
  const configModule = await import('./lib/config.js');
  const config = configModule.default;
  await config._waitForInit();
  const port = process.env.PORT || config.server.port || 3080;
  
  // Import the Socket.IO base controller to hook our IPC socket bridge
  const baseController = await import('./lib/server/socket.io/controllers/base.js');
  
  return {
    handleConnection: baseController.handleConnection,
    port
  };
}

function createWindow(port) {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    title: "MioChat Desktop",
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false
    }
  });

  mainWindow.loadURL(`http://localhost:${port}`);

  // Mock Socket.IO connection object to feed into the backend controllers
  class MockSocket extends EventEmitter {
    constructor(win) {
      super();
      this.win = win;
      // Simulates socket.userInfo generated by authSocketConnection middleware
      this.userInfo = {
        id: 'admin',
        ip: '127.0.0.1',
        isAdmin: true,
        origin: 'electron',
        firstLogin: true
      };
    }

    emit(event, ...args) {
      if (event === 'message') {
        // Forward message payload to frontend window via IPC
        if (this.win && !this.win.isDestroyed()) {
          this.win.webContents.send('socket-to-client', args[0]);
        }
      } else {
        if (this.win && !this.win.isDestroyed()) {
          this.win.webContents.send('socket-to-client-event', { event, args });
        }
      }
      super.emit(event, ...args);
    }
  }

  // Set up IPC event handlers to bridge to backend mock socket
  ipcMain.on('client-connect', (event) => {
    console.log('[Electron Main] IPC Connection requested by frontend');
    if (mockSocketInstance) {
      mockSocketInstance.emit('disconnect');
    }

    mockSocketInstance = new MockSocket(mainWindow);

    try {
      backendAPIs.handleConnection(mockSocketInstance);
      event.reply('socket-connected');
      console.log('[Electron Main] Client connected and mock session established');
    } catch (err) {
      console.error('[Electron Main] Error bridging client connection:', err);
    }
  });

  ipcMain.on('client-to-socket', (event, message) => {
    if (mockSocketInstance) {
      mockSocketInstance.emit('message', message);
    }
  });

  ipcMain.on('client-to-socket-interrupt', (event, data) => {
    if (mockSocketInstance) {
      mockSocketInstance.emit('interruptGeneration', data);
    }
  });

  ipcMain.on('client-to-socket-interact', (event, data) => {
    if (mockSocketInstance) {
      mockSocketInstance.emit('tool:interact', data);
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
    if (mockSocketInstance) {
      mockSocketInstance.emit('disconnect');
      mockSocketInstance = null;
    }
  });
}

app.whenReady().then(async () => {
  try {
    backendAPIs = await bootstrapBackend();
    createWindow(backendAPIs.port);
  } catch (err) {
    console.error('[Electron Main] Bootstrapping failed:', err);
    app.quit();
  }
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow(backendAPIs ? backendAPIs.port : 3080);
  }
});
