APIList:
  - url: http://127.0.0.1:3080/api/mjDefault
    remark: '[PixArt][mjDefault]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjCinematic
    remark: '[PixArt][mjCinematic]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjPhotographic
    remark: '[PixArt][mjPhotographic]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjAnime
    remark: '[PixArt][mjAnime]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjManga
    remark: '[PixArt][mjManga]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjDigital
    remark: '[PixArt][mjDigital]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjPixel
    remark: '[PixArt][mjPixel]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjFantasy
    remark: '[PixArt][mjFantasy]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mjNeonpunk
    remark: '[PixArt][mjNeonpunk]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mj3D
    remark: '[PixArt][mj3D]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/3Guofeng3_v34
    remark: '[二次元][3Guofeng3_v34]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/anythingv3_0-pruned
    remark: '[二次元][anythingv3_0-pruned]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/anything-v4
    remark: '[二次元][anything-v4]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/anythingV5_PrtRE
    remark: '[二次元][anythingV5_PrtRE]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/AOM3A3_orangemixs
    remark: '[二次元][AOM3A3_orangemixs]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/blazing_drive_v10g
    remark: '[二次元][blazing_drive_v10g]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/cetusMix_Version35
    remark: '[二次元][cetusMix_Version35]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/childrensStories_v1SemiReal
    remark: '[二次元][childrensStories_v1SemiReal]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/Counterfeit_v30
    remark: '[二次元][Counterfeit_v30]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/cuteyukimixAdorable_midchapter3
    remark: '[二次元][cuteyukimixAdorable_midchapter3]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/dalcefo_v4
    remark: '[二次元][dalcefo_v4]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/pastelMixStylizedAnime_pruned_fp16
    remark: '[二次元][pastelMixStylizedAnime_pruned_fp16]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/EimisAnimeDiffusion_V1
    remark: '[二次元][EimisAnimeDiffusion_V1]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/mechamix_v10
    remark: '[二次元][mechamix_v10]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/meinamix_meinaV9
    remark: '[二次元][meinamix_meinaV9]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/meinamix_meinaV11
    remark: '[二次元][meinamix_meinaV11]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/neverendingDream_v122
    remark: '[坤次元][neverendingDream_v122]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/dreamshaper_7
    remark: '[坤次元][dreamshaper_7]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/dreamshaper_8
    remark: '[坤次元][dreamshaper_8]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/edgeOfRealism_eorV20
    remark: '[坤次元][edgeOfRealism_eorV20]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/revAnimated_v122
    remark: '[坤次元][revAnimated_v122]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/rundiffusionFX25D_v10
    remark: '[坤次元][rundiffusionFX25D_v10]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/rundiffusionFX_v10
    remark: '[坤次元][rundiffusionFX_v10]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/shoninsBeautiful_v10
    remark: '[坤次元][shoninsBeautiful_v10]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/toonyou_beta6
    remark: '[坤次元][toonyou_beta6]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/absolutereality_v181
    remark: '[坤次元][absolutereality_v181]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/childrensStories_v13D
    remark: '[坤次元][childrensStories_v13D]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/childrensStories_v1ToonAnime
    remark: '[坤次元][childrensStories_v1ToonAnime]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/deliberate_v2
    remark: '[坤次元][deliberate_v2]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/deliberate_v3
    remark: '[坤次元][deliberate_v3]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/dreamlike-anime-1
    remark: '[坤次元][dreamlike-anime-1]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/dreamshaper_6BakedVae
    remark: '[坤次元][dreamshaper_6BakedVae]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/elldreths-vivid-mix
    remark: '[坤次元][elldreths-vivid-mix]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/lyriel_v16
    remark: '[坤次元][lyriel_v16]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/absolutereality_V16
    remark: '[三次元][absolutereality_V16]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/epicrealism_naturalSinRC1VAE
    remark: '[三次元][epicrealism_naturalSinRC1VAE]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/ICantBelieveItsNotPhotography_seco
    remark: '[三次元][ICantBelieveItsNotPhotography_seco]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/juggernaut_aftermath
    remark: '[三次元][juggernaut_aftermath]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/amIReal_V41
    remark: '[三次元][amIReal_V41]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/majicmixRealistic_v4
    remark: '[三次元][majicmixRealistic_v4]'
    account_id: ''
    account_password: ''
    token: ''
  - url: http://127.0.0.1:3080/api/cyberrealistic_v33
    remark: '[三次元][cyberrealistic_v33]'
    account_id: ''
    account_password: ''
    token: ''
